### ISSUE TITLE
arecord main 788 audio open error Device or resource busy

### ISSUE THREAD

**Issue by emacsLover** [synesthesiam/rhasspy#29]
Thank you for that outstandingly well documented piece of work.

Using the `hotword` does not work at all, while using the `wake` button detects
my voice `"..what time is it.."`. Both methods return errors though.

    docker run -it -p 12101:12101 -v "$HOME/.config/rhasspy/profiles:/profiles"  --device /dev/snd:/dev/snd synesthesiam/rhasspy-server:latest  --user-profiles /profiles  --profile en

## Hotword

    ynesthesiam/rhasspy-server:latest  --user-profiles /profiles  --profile en                                                   
    DEBUG:__main__:Namespace(host='0.0.0.0', port=12101, profile='en', set=[], ssl=None, system_profiles='/usr/share/rhasspy/profi
    les', user_profiles='/profiles')                                                                                             
    DEBUG:RhasspyCore:Loaded profile from /profiles/en/profile.json
    DEBUG:RhasspyCore:Profile files will be written to /profiles/en
    DEBUG:root:Loading default profile settings from /usr/share/rhasspy/profiles/defaults.json
    DEBUG:WebSocketObserver: -> started
    DEBUG:DialogueManager: -> started
    DEBUG:DialogueManager:started -> loading
    DEBUG:DialogueManager:Loading actors
    DEBUG:DialogueManager:Actors created. Waiting for ['recorder', 'player', 'speech', 'wake', 'command', 'decoder', 'recognizer',
     'handler', 'sentence_generator', 'speech_trainer', 'intent_trainer', 'word_pronouncer'] to start.                           
    DEBUG:ARecordAudioRecorder: -> started
    DEBUG:APlayAudioPlayer: -> started
    DEBUG:EspeakSentenceSpeaker: -> started
    DEBUG:PocketsphinxWakeListener: -> started
    DEBUG:WebrtcvadCommandListener: -> started
    DEBUG:PocketsphinxDecoder: -> started
    DEBUG:FsticuffsRecognizer: -> started
    DEBUG:DummyIntentHandler: -> started
    DEBUG:JsgfSentenceGenerator: -> started
    DEBUG:PocketsphinxSpeechTrainer: -> started
    DEBUG:FsticuffsIntentTrainer: -> started
    DEBUG:PhonetisaurusPronounce: -> started
    DEBUG:EspeakSentenceSpeaker:started -> ready
    DEBUG:PocketsphinxWakeListener:Loading wake decoder with hmm=/profiles/en/acoustic_model, dict=/profiles/en/dictionary.txt
    DEBUG:WebrtcvadCommandListener:started -> loaded
    DEBUG:FsticuffsRecognizer:Using stop words at /usr/share/rhasspy/profiles/en/stop_words.txt
    DEBUG:PocketsphinxWakeListener:started -> loaded
    DEBUG:FsticuffsRecognizer:started -> loaded
    DEBUG:DialogueManager:recorder started
    DEBUG:PocketsphinxDecoder:Loading decoder with hmm=/profiles/en/acoustic_model, dict=/profiles/en/dictionary.txt, lm=/profiles
    /en/language_model.txt                                                                                                       
    DEBUG:DialogueManager:player started
    DEBUG:PocketsphinxDecoder:started -> loaded
    DEBUG:DialogueManager:handler started
    DEBUG:DialogueManager:sentence_generator started
    DEBUG:DialogueManager:speech_trainer started
    DEBUG:DialogueManager:intent_trainer started
    DEBUG:DialogueManager:word_pronouncer started
    DEBUG:DialogueManager:speech started
    DEBUG:DialogueManager:command started
    DEBUG:DialogueManager:wake started
    DEBUG:DialogueManager:recognizer started
    DEBUG:DialogueManager:decoder started
    INFO:DialogueManager:Actors loaded
    DEBUG:DialogueManager:loading -> ready
    INFO:DialogueManager:Automatically listening for wake word
    DEBUG:DialogueManager:ready -> asleep
    DEBUG:PocketsphinxWakeListener:loaded -> listening
    INFO:__main__:Started
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:__main__:Starting web server at http://0.0.0.0:12101
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    DEBUG:PocketsphinxWakeListener:Hotword detected (okay okay)
    DEBUG:DialogueManager:Awake!
    DEBUG:DialogueManager:asleep -> awake
    DEBUG:PocketsphinxWakeListener:listening -> loaded
    DEBUG:APlayAudioPlayer:['aplay', '-q', '/usr/share/rhasspy/etc/wav/beep_hi.wav']
    DEBUG:WebrtcvadCommandListener:loaded -> listening
    DEBUG:ARecordAudioRecorder:recording -> started
    DEBUG:ARecordAudioRecorder:Stopped recording from microphone (arecord)
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/usr/local/lib/python3.6/dist-packages/gevent/threading.py", line 177, in run
        super(Thread, self).run()
      File "/usr/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 376, in process_data
        data = self.record_proc.stdout.read(self.chunk_size)
    AttributeError: 'NoneType' object has no attribute 'stdout'

Some attempts/hotword detections later, the error contains:
`arecord: main:788: audio open error: Device or resource busy`

    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    DEBUG:PocketsphinxWakeListener:Hotword detected (okay okay)
    DEBUG:DialogueManager:Awake!
    DEBUG:DialogueManager:asleep -> awake
    DEBUG:PocketsphinxWakeListener:listening -> loaded
    DEBUG:APlayAudioPlayer:['aplay', '-q', '/usr/share/rhasspy/etc/wav/beep_hi.wav']
    DEBUG:WebrtcvadCommandListener:loaded -> listening
    DEBUG:ARecordAudioRecorder:recording -> started
    DEBUG:ARecordAudioRecorder:Stopped recording from microphone (arecord)
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    arecord: main:788: audio open error: Device or resource busy
    WARNING:WebrtcvadCommandListener:Timeout
    DEBUG:WebrtcvadCommandListener:listening -> loaded
    DEBUG:ARecordAudioRecorder:recording -> started
    DEBUG:DialogueManager:awake -> decoding
    DEBUG:APlayAudioPlayer:['aplay', '-q', '/usr/share/rhasspy/etc/wav/beep_lo.wav']
    DEBUG:PocketsphinxDecoder:rate=16000, width=2, channels=1.
    DEBUG:ARecordAudioRecorder:Stopped recording from microphone (arecord)
    DEBUG:PocketsphinxDecoder:Decoded WAV in 0.0007455348968505859 second(s)
    DEBUG:DialogueManager: (confidence=0)
    DEBUG:DialogueManager:decoding -> recognizing
    DEBUG:FsticuffsRecognizer:Recognized 0 intent(s)
    DEBUG:DialogueManager:{'text': '', 'intent': {'name': '', 'confidence': 0}, 'entities': [], 'speech_confidence': 0}
    DEBUG:DialogueManager:recognizing -> handling
    DEBUG:WebSocketObserver:{"text": "", "intent": {"name": "", "confidence": 0}, "entities": [], "speech_confidence": 0, "slots":
     {}}                                                                                                                         
    DEBUG:DialogueManager:handling -> ready
    INFO:DialogueManager:Automatically listening for wake word
    DEBUG:DialogueManager:ready -> asleep
    DEBUG:PocketsphinxWakeListener:loaded -> listening
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)

## Wake button (WebUI)

    ynesthesiam/rhasspy-server:latest  --user-profiles /profiles  --profile en                                                   
    DEBUG:__main__:Namespace(host='0.0.0.0', port=12101, profile='en', set=[], ssl=None, system_profiles='/usr/share/rhasspy/profi
    les', user_profiles='/profiles')                                                                                             
    DEBUG:RhasspyCore:Loaded profile from /profiles/en/profile.json
    DEBUG:RhasspyCore:Profile files will be written to /profiles/en
    DEBUG:root:Loading default profile settings from /usr/share/rhasspy/profiles/defaults.json
    DEBUG:WebSocketObserver: -> started
    DEBUG:DialogueManager: -> started
    DEBUG:DialogueManager:started -> loading
    DEBUG:DialogueManager:Loading actors
    DEBUG:DialogueManager:Actors created. Waiting for ['recorder', 'player', 'speech', 'wake', 'command', 'decoder', 'recognizer',
     'handler', 'sentence_generator', 'speech_trainer', 'intent_trainer', 'word_pronouncer'] to start.                           
    DEBUG:ARecordAudioRecorder: -> started
    DEBUG:APlayAudioPlayer: -> started
    DEBUG:EspeakSentenceSpeaker: -> started
    DEBUG:PocketsphinxWakeListener: -> started
    DEBUG:WebrtcvadCommandListener: -> started
    DEBUG:PocketsphinxDecoder: -> started
    DEBUG:FsticuffsRecognizer: -> started
    DEBUG:DummyIntentHandler: -> started
    DEBUG:JsgfSentenceGenerator: -> started
    DEBUG:PocketsphinxSpeechTrainer: -> started
    DEBUG:FsticuffsIntentTrainer: -> started
    DEBUG:PhonetisaurusPronounce: -> started
    DEBUG:EspeakSentenceSpeaker:started -> ready
    DEBUG:PocketsphinxWakeListener:Loading wake decoder with hmm=/profiles/en/acoustic_model, dict=/profiles/en/dictionary.txt
    DEBUG:WebrtcvadCommandListener:started -> loaded
    DEBUG:FsticuffsRecognizer:Using stop words at /usr/share/rhasspy/profiles/en/stop_words.txt
    DEBUG:PocketsphinxWakeListener:started -> loaded
    DEBUG:FsticuffsRecognizer:started -> loaded
    DEBUG:DialogueManager:recorder started
    DEBUG:PocketsphinxDecoder:Loading decoder with hmm=/profiles/en/acoustic_model, dict=/profiles/en/dictionary.txt, lm=/profiles
    /en/language_model.txt                                                                                                       
    DEBUG:DialogueManager:player started
    DEBUG:PocketsphinxDecoder:started -> loaded
    DEBUG:DialogueManager:handler started
    DEBUG:DialogueManager:sentence_generator started
    DEBUG:DialogueManager:speech_trainer started
    DEBUG:DialogueManager:intent_trainer started
    DEBUG:DialogueManager:word_pronouncer started
    DEBUG:DialogueManager:speech started
    DEBUG:DialogueManager:command started
    DEBUG:DialogueManager:wake started
    DEBUG:DialogueManager:recognizer started
    DEBUG:DialogueManager:decoder started
    INFO:DialogueManager:Actors loaded
    DEBUG:DialogueManager:loading -> ready
    INFO:DialogueManager:Automatically listening for wake word
    DEBUG:DialogueManager:ready -> asleep
    DEBUG:PocketsphinxWakeListener:loaded -> listening
    INFO:__main__:Started
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:__main__:Starting web server at http://0.0.0.0:12101
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    DEBUG:DialogueManager:asleep -> awake
    DEBUG:PocketsphinxWakeListener:listening -> loaded
    DEBUG:APlayAudioPlayer:['aplay', '-q', '/usr/share/rhasspy/etc/wav/beep_hi.wav']
    DEBUG:WebrtcvadCommandListener:loaded -> listening
    DEBUG:ARecordAudioRecorder:recording -> started
    DEBUG:ARecordAudioRecorder:Stopped recording from microphone (arecord)
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/usr/local/lib/python3.6/dist-packages/gevent/threading.py", line 177, in run
        super(Thread, self).run()
      File "/usr/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 376, in process_data
        data = self.record_proc.stdout.read(self.chunk_size)
    RuntimeError: reentrant call inside <_io.BufferedReader>
    
    DEBUG:WebrtcvadCommandListener:Voice command started
    DEBUG:WebrtcvadCommandListener:Voice command finished
    DEBUG:WebrtcvadCommandListener:listening -> loaded
    DEBUG:ARecordAudioRecorder:recording -> started
    DEBUG:DialogueManager:awake -> decoding
    DEBUG:APlayAudioPlayer:['aplay', '-q', '/usr/share/rhasspy/etc/wav/beep_lo.wav']
    DEBUG:PocketsphinxDecoder:rate=16000, width=2, channels=1.
    DEBUG:ARecordAudioRecorder:Stopped recording from microphone (arecord)
    DEBUG:PocketsphinxDecoder:Decoded WAV in 1.5138514041900635 second(s)
    DEBUG:PocketsphinxDecoder:Transcription confidence: 0.0008520040640515801
    DEBUG:PocketsphinxDecoder:time is it
    DEBUG:DialogueManager:time is it (confidence=0.0008520040640515801)
    DEBUG:DialogueManager:decoding -> recognizing
    DEBUG:FsticuffsRecognizer:Recognized 0 intent(s)
    DEBUG:DialogueManager:{'text': 'time is it', 'intent': {'name': '', 'confidence': 0}, 'entities': [], 'speech_confidence': 0.0
    008520040640515801}                                                                                                          
    DEBUG:DialogueManager:recognizing -> handling
    DEBUG:WebSocketObserver:{"text": "time is it", "intent": {"name": "", "confidence": 0}, "entities": [], "speech_confidence": 0
    .0008520040640515801, "slots": {}}                                                                                           
    DEBUG:DialogueManager:handling -> ready
    INFO:DialogueManager:Automatically listening for wake word
    DEBUG:DialogueManager:ready -> asleep
    DEBUG:PocketsphinxWakeListener:loaded -> listening
    DEBUG:ARecordAudioRecorder:started -> recording
    DEBUG:ARecordAudioRecorder:['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'default:CARD=seeed4
    micvoicec']                                                                                                                  
    DEBUG:ARecordAudioRecorder:Recording from microphone (arecord)
    Exception in thread Thread-20:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/usr/local/lib/python3.6/dist-packages/gevent/threading.py", line 177, in run
        super(Thread, self).run()
      File "/usr/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 376, in process_data
        data = self.record_proc.stdout.read(self.chunk_size)
    AttributeError: 'NoneType' object has no attribute 'stdout'

## Environment

    uname -a
    arecord -l

    Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
    **** List of CAPTURE Hardware Devices ****
    card 1: seeed4micvoicec [seeed-4mic-voicecard], device 0: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 []
      Subdevices: 0/1
      Subdevice #0: subdevice #0

### *home/pi*.config/rhasspy/profiles/en/profile.json

    {
        "microphone": {
            "arecord": {
                "device": "default:CARD=seeed4micvoicec"
            },
            "pyaudio": {
                "device": "3"
            },
            "system": "arecord"
        },
        "wake": {
            "pocketsphinx": {
                "keyphrase": "okay okay"
            },
            "system": "pocketsphinx"
        }
    }

**Comment by synesthesiam** [comment]
Thanks for the feedback!

The errors I see suggest that the `arecord` process is failing to start. Does running the same `arecord` command that Rhasspy runs work for you?

```bash
$ arecord -q -r 16000 -f S16_LE -c 1 -t raw -D 'default:CARD=seeed4 micvoicec'
```

I've found that getting Docker to property access the microphone has been the most difficult part of Rhasspy. Sometimes, mapping `/dev/snd` with `-v` instead of `--device` works too, or using the `--privileged` flag.

**Comment by emacsLover** [comment]
Thank you for taking care so fast.

**Comment by emacsLover** [comment]
I went ahead with `arecord` testing:

****Pass****
`$ aplay test.wav` returns clear recorded voice

    arecord -D 'default' test.wav

****Fail****
`$ aplay test.wav` returns distorted noise

    arecord -q -r 16000 -f S16_LE -c 1 -t raw -D 'default' test.wav

**Comment by synesthesiam** [comment]
Rhasspy crashing when you save the profile should definitely not be happening. Was there anything in the log to indicate what went wrong? Can you modify your profile.json file directly before Rhasspy loads?

If we can't get `arecord` to work directly, there are two other options: (1) try the [PyAudio](https://rhasspy.readthedocs.io/en/latest/audio-input/#pyaudio) input system, and (2) I can add an option to call out to an arbitrary program to record audio, which you can fill with the working arguments to `arecord` (that Rhasspy crashes on for some reason).

Let me know!
