### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by emacsLover** [synesthesiam/rhasspy#30]
Any chance to see the debug log as file directly instead in the hassio webui? Any other emacs solution is most welcome as well

**Comment by synesthesiam** [comment]
The log messages are output using Python's `logging` module, which I believe goes to `stderr` by default. I'm not aware of any way to get this out of Hass.IO except through the webui, unless you have the portainer add-on installed.

Every log message is also being published by Rhasspy to a websocket at `ws://your-server:12101/api/events/log`  This is what the Rhasspy web UI is pulling from.
